version: '3'
services:
  app:
    platform: "linux/amd64"
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    #  - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sac
    #  - REDIS_URI=redis://redis:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  #redis:
  #  image: redis:latest
  #  ports:
  #    - 6379:6379
